Repository portainer/portainer, pull requests merged in 2018-05, with the labels that each got.

#1861 fix(log-viewer): strip headers in container logs when TTY is disabled
  app/docker/helpers/logHelper.js
  app/docker/rest/container.js
  app/docker/rest/response/handlers.js
  app/docker/rest/service.js
  app/docker/rest/task.js
  app/docker/services/containerService.js
  app/docker/services/serviceService.js
  app/docker/services/taskService.js
  app/docker/views/containers/logs/containerLogsController.js
Labels: docker-image-available

#1866 feat(brutforce-protection): add rate limiter
  api/http/handler/auth.go
  api/http/security/rate_limiter.go
  api/http/security/rate_limiter_test.go
  api/http/server.go
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1872 feat(settings): allow hide container with label with no value (#1860)
  app/portainer/views/settings/settings.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1878 Switching container port mapping around.
  app/docker/views/containers/edit/container.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1625 fix(service-details) avoid sending unmodified values in service update
  app/docker/views/services/edit/serviceController.js
Labels: contrib/func-review-approved

#1902 feat(sidebar): update endpoint selection UX
  app/portainer/views/sidebar/sidebar.html
  app/portainer/views/sidebar/sidebarController.js
  assets/css/app.css
Labels: area/sidebar, kind/enhancement

#1901 fix(websocket): copy Host header during websocket request proxy
  api/http/handler/websocket.go
Labels: status/awaiting-feedback

#1914 #1894 Add lines field in container logs viewer
  app/docker/components/log-viewer/log-viewer.js
  app/docker/components/log-viewer/logViewer.html
  app/docker/views/containers/logs/containerlogs.html
  app/docker/views/services/logs/servicelogs.html
  app/docker/views/tasks/logs/tasklogs.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated
