Repository portainer/portainer, pull requests merged in 2018-08, with the labels that each got.

#2121 feat(container-details)
  app/docker/views/containers/edit/container.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2126 Replace filter for counting running and stopped containers
  app/docker/filters/filters.js
  app/docker/views/dashboard/dashboard.html
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2130 Add .vscode to .gitignore
  .gitignore
Labels: area/project, contrib/ready-to-merge

#2119 feat(templates): re-introduce external template management
  api/cmd/portainer/main.go
  api/http/handler/settings/settings_public.go
  api/http/handler/settings/settings_update.go
  api/http/handler/templates/handler.go
  api/http/handler/templates/template_list.go
  api/http/server.go
  api/portainer.go
  app/portainer/models/settings.js
  app/portainer/views/settings/settings.html
  app/portainer/views/settings/settingsController.js
  app/portainer/views/templates/templates.html
  app/portainer/views/templates/templatesController.js
Labels: docker-image-available

#2108 feat(volume-creation) : NFS volume creation (#2083)
  app/docker/components/volumesNFSForm/volumes-nfs-form.js
  app/docker/components/volumesNFSForm/volumesNFSFormModel.js
  app/docker/components/volumesNFSForm/volumesnfsForm.html
  app/docker/views/volumes/create/createVolumeController.js
  app/docker/views/volumes/create/createvolume.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2078 feat(container-creation): container add/drop capabilities on creation (#468)
  app/docker/components/container-capabilities/container-capabilities.js
  app/docker/components/container-capabilities/containerCapabilities.html
  app/docker/models/containerCapabilities.js
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2144 chore(ci): remove codefresh workflows
  .codefresh/codefresh_branch.yml
  .codefresh/codefresh_pullrequest.yml
Labels: area/ci

#2152 point filebrowser template to correct image
  templates.json
Labels: area/templates, kind/enhancement

#2146 Adds scripts to package.json
  package.json
Labels: area/build-system, kind/enhancement

#2156 chore(project): update lodash version to 4.17.10
  package.json
  yarn.lock
Labels: kind/update-dependency

#2141 Change order of container recreation
  app/docker/views/containers/edit/containerController.js
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2147 Show correct number of cpus and total memory for swarm
  api/docker/snapshot.go
  app/docker/views/dashboard/dashboard.html
  app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2163 feat(containers): add runtime option in the container creation(#2162)
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2164 Add option to update restart-policy for containers
  app/docker/components/container-restart-policy/container-restart-policy-controller.js
  app/docker/components/container-restart-policy/container-restart-policy.html
  app/docker/components/container-restart-policy/container-restart-policy.js
  app/docker/rest/container.js
  app/docker/services/containerService.js
  app/docker/views/containers/edit/container.html
  app/docker/views/containers/edit/containerController.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2122 feat(network-creation): macvlan driver for swarm mode (#2082)
  app/docker/components/datatables/macvlan-nodes-datatable/macvlanNodesDatatable.html
  app/docker/components/datatables/macvlan-nodes-datatable/macvlanNodesDatatable.js
  app/docker/components/network-macvlan-form/network-macvlan-form.js
  app/docker/components/network-macvlan-form/networkMacvlanForm.html
  app/docker/components/network-macvlan-form/networkMacvlanFormController.js
  app/docker/components/network-macvlan-form/networkMacvlanFormModel.js
  app/docker/models/network.js
  app/docker/views/networks/create/createNetworkController.js
  app/docker/views/networks/create/createnetwork.html
  assets/css/app.css
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2158 Refactor container creation order
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: area/container-creation, container/edit, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated, kind/enhancement

#2159 feat(console): Adds custom commands based on container labels
  app/constants.js
  app/docker/views/containers/console/containerConsoleController.js
  app/docker/views/containers/console/containerconsole.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2137 #960 feat(UAC): change default ownership to admins for externally created resources
  api/bolt/migrator/migrate_dbversion13.go
  api/bolt/migrator/migrator.go
  api/http/handler/resourcecontrols/resourcecontrol_create.go
  api/http/handler/resourcecontrols/resourcecontrol_update.go
  api/http/handler/stacks/stack_delete.go
  api/http/handler/stacks/stack_file.go
  api/http/handler/stacks/stack_inspect.go
  api/http/handler/stacks/stack_migrate.go
  api/http/handler/stacks/stack_update.go
  api/http/proxy/access_control.go
  api/http/proxy/containers.go
  api/http/proxy/networks.go
  api/http/proxy/services.go
  api/http/proxy/tasks.go
  api/http/proxy/volumes.go
  api/http/security/authorization.go
  api/portainer.go
  api/swagger.yaml
  app/docker/components/datatables/configs-datatable/configsDatatable.html
  app/docker/components/datatables/containers-datatable/containersDatatable.html
  app/docker/components/datatables/networks-datatable/networksDatatable.html
  app/docker/components/datatables/secrets-datatable/secretsDatatable.html
  app/docker/components/datatables/services-datatable/servicesDatatable.html
  app/docker/components/datatables/volumes-datatable/volumesDatatable.html
  app/docker/views/containers/edit/containerController.js
  app/portainer/components/accessControlPanel/porAccessControlPanel.html
  app/portainer/components/accessControlPanel/porAccessControlPanelController.js
  app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
  app/portainer/models/resourceControl.js
  app/portainer/services/api/resourceControlService.js
Labels: breaking-changes, contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2127 fix(services): replicas numbers display (#1990)
  app/docker/components/datatables/services-datatable/servicesDatatable.html
  app/docker/filters/filters.js
  app/docker/helpers/constraintsHelper.js
  app/docker/models/task.js
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2196 Fix action buttons in stacks view
  app/portainer/views/stacks/edit/stackController.js
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2191 feat(motd): add the ability to display motd and dimiss information panels
  api/crypto/ecdsa.go
  api/crypto/md5.go
  api/http/client/client.go
  api/http/handler/handler.go
  api/http/handler/motd/handler.go
  api/http/handler/motd/motd.go
  api/http/server.go
  api/portainer.go
  app/constants.js
  app/docker/views/dashboard/dashboard.html
  app/docker/views/dashboard/dashboardController.js
  app/portainer/components/information-panel/information-panel.js
  app/portainer/components/information-panel/informationPanel.html
  app/portainer/models/motd.js
  app/portainer/rest/motd.js
  app/portainer/services/api/motdService.js
  app/portainer/services/localStorage.js
  app/portainer/services/stateManager.js
  app/portainer/views/home/home.html
  app/portainer/views/home/homeController.js
Labels: kind/feature

#2189 #1911 feat(configs): implements clone config feature
  app/docker/__module.js
  app/docker/components/datatables/configs-datatable/configsDatatable.html
  app/docker/views/configs/create/createConfigController.js
  app/docker/views/configs/create/createconfig.html
  app/docker/views/configs/edit/config.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2200 feat(networks): Add network details (#1717)
  app/docker/components/datatables/networks-datatable/networksDatatable.html
  app/docker/models/network.js
  app/docker/views/networks/edit/network.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2167 feat(security): update secured headers and sanitize team name
  api/http/handler/file/handler.go
  api/http/security/bouncer.go
  app/portainer/views/teams/teamsController.js
Labels: area/security

#2210 Populate TemplatesURL from Command Line
  api/cmd/portainer/main.go
Labels: area/templates, contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#2218 #2174 fix(images): Fix to allow both tar and gzip images
  app/docker/views/images/import/importimage.html
Labels: contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated
