Repository portainer/portainer, pull requests merged in 2018-10, with the labels that each got.

#2278 Add ability to duplicate a stack
  api/http/handler/stacks/stack_migrate.go
  api/swagger.yaml
  app/portainer/components/stack-duplication-form/stack-duplication-form-controller.js
  app/portainer/components/stack-duplication-form/stack-duplication-form.html
  app/portainer/components/stack-duplication-form/stack-duplication-form.js
  app/portainer/services/api/stackService.js
  app/portainer/views/stacks/edit/stack.html
  app/portainer/views/stacks/edit/stackController.js
Labels: status/5-merge

#2309 Snapshot endpoints and start server in parallel
  api/cron/scheduler.go
Labels: status/5-merge

#2322 fix(rest): remove x frame option from rest headers
  api/http/handler/file/handler.go
  api/http/security/bouncer.go
Labels: status/5-merge

#2329 Sort tasks in alphabetical order on refresh
  app/docker/views/swarm/visualizer/swarmvisualizer.html
Labels: status/5-merge

#2326 Sort the values in the network list
  app/docker/components/datatables/container-networks-datatable/containerNetworksDatatable.html
  app/docker/views/containers/create/createcontainer.html
  app/docker/views/services/create/createservice.html
  app/portainer/views/templates/templates.html
Labels: area/UX, kind/enhancement, status/5-merge

#2328 Display node name instead of hostname when applicable
  app/docker/components/datatables/nodes-datatable/nodesDatatable.html
  app/docker/views/swarm/visualizer/swarmvisualizer.html
Labels: status/5-merge

#2338 Move volume id to query params
  app/agent/rest/browse.js
  app/agent/services/volumeBrowserService.js
Labels: area/volume-browser, bug/confirmed, kind/bug, status/5-merge

#2255 Upgrade the engine details view to host view
  app/agent/rest/host.js
  app/agent/services/agentService.js
  app/docker/__module.js
  app/docker/components/dockerSidebarContent/dockerSidebarContent.html
  app/docker/components/host-overview/host-overview.html
  app/docker/components/host-overview/host-overview.js
  app/docker/components/host-view-panels/devices-panel/devices-panel.html
  app/docker/components/host-view-panels/devices-panel/devices-panel.js
  app/docker/components/host-view-panels/disks-panel/disks-panel.html
  app/docker/components/host-view-panels/disks-panel/disks-panel.js
  app/docker/components/host-view-panels/engine-details-panel/engine-details-panel.html
  app/docker/components/host-view-panels/engine-details-panel/engine-details-panel.js
  app/docker/components/host-view-panels/host-details-panel/host-details-panel.html
  app/docker/components/host-view-panels/host-details-panel/host-details-panel.js
  app/docker/components/host-view-panels/node-availability-select/node-availability-select-controller.js
  app/docker/components/host-view-panels/node-availability-select/node-availability-select.html
  app/docker/components/host-view-panels/node-availability-select/node-availability-select.js
  app/docker/components/host-view-panels/node-labels-table/node-labels-table-controller.js
  app/docker/components/host-view-panels/node-labels-table/node-labels-table.html
  app/docker/components/host-view-panels/node-labels-table/node-labels-table.js
  app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel-controller.js
  app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel.html
  app/docker/components/host-view-panels/swarm-node-details-panel/swarm-node-details-panel.js
  app/docker/services/nodeService.js
  app/docker/views/engine/engine.html
  app/docker/views/engine/engineController.js
  app/docker/views/host/host-view-controller.js
  app/docker/views/host/host-view.html
  app/docker/views/host/host-view.js
  app/docker/views/nodes/edit/node.html
  app/docker/views/nodes/edit/nodeController.js
  app/docker/views/nodes/node-details/node-details-view-controller.js
  app/docker/views/nodes/node-details/node-details-view.html
  app/docker/views/nodes/node-details/node-details-view.js
Labels: status/5-merge

#2325 fix(containers): docker-runc
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: status/5-merge

#2337 Add host file browser with upload/download files
  app/agent/components/file-uploader/file-uploader-controller.js
  app/agent/components/file-uploader/file-uploader.html
  app/agent/components/file-uploader/file-uploader.js
  app/agent/components/files-datatable/files-datatable.html
  app/agent/components/files-datatable/files-datatable.js
  app/agent/components/host-browser/host-browser-controller.js
  app/agent/components/host-browser/host-browser.html
  app/agent/components/host-browser/host-browser.js
  app/agent/components/volume-browser/volume-browser-datatable/volume-browser-datatable.js
  app/agent/components/volume-browser/volumeBrowser.html
  app/agent/services/hostBrowserService.js
  app/agent/services/volumeBrowserService.js
  app/docker/__module.js
  app/docker/components/dockerSidebarContent/docker-sidebar-content.js
  app/docker/components/host-overview/host-overview.html
  app/docker/components/host-overview/host-overview.js
  app/docker/components/host-view-panels/host-details-panel/host-details-panel.html
  app/docker/components/host-view-panels/host-details-panel/host-details-panel.js
  app/docker/views/host/host-browser-view/host-browser-view-controller.js
  app/docker/views/host/host-browser-view/host-browser-view.html
  app/docker/views/host/host-browser-view/host-browser-view.js
  app/docker/views/host/host-view.html
  app/docker/views/nodes/node-browser/node-browser-controller.js
  app/docker/views/nodes/node-browser/node-browser.html
  app/docker/views/nodes/node-browser/node-browser.js
  app/docker/views/nodes/node-details/node-details-view.html
Labels: status/5-merge

#2340 feat(ux): Redirect from init/admin to home when admin already exists
  app/portainer/views/init/admin/initAdminController.js
Labels: status/5-merge

#2371 fix : exclude cache from the Memory Usage chart to avoid misinterpret…
  app/docker/models/container.js
Labels: status/5-merge

#2361 Create job execution API
  api/archive/tar.go
  api/cmd/portainer/main.go
  api/docker/client.go
  api/docker/jobservice.go
  api/http/handler/endpoints/endpoint_job.go
  api/http/handler/endpoints/handler.go
  api/http/proxy/build.go
  api/http/server.go
  api/portainer.go
Labels: status/5-merge

#2392 docs(swagger): document the endpoint job execution
  api/swagger.yaml
Labels: area/documentation

#2393 refactor(app): refactor unauthenticated state management
  app/app.js
  app/config.js
  app/portainer/services/authentication.js
Labels: area/authentication, kind/refactor

#2387 Fixed the build status badge on the README page
  README.md
Labels: area/documentation, area/project, status/5-merge

#2396 fix(sorting): Alphabetically sort configs and secrets in service details select box
  app/docker/views/services/create/includes/config.html
  app/docker/views/services/create/includes/secret.html
  app/docker/views/services/edit/includes/configs.html
  app/docker/views/services/edit/includes/secrets.html
Labels: status/5-merge

#2383 Display cache in memory usage chart
  app/docker/models/container.js
  app/docker/views/containers/stats/containerStatsController.js
  app/portainer/services/chartService.js
Labels: status/5-merge

#2384 feat(containers): add logdriver configuration to container create view
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: status/5-merge

#2404 Updates for swagger-codegen
  api/swagger.yaml
  api/swagger_config.json
Labels: area/api, area/documentation, kind/enhancement, status/5-merge

#2377 chore(log-viewer): enhance the log-viewer with parameters `since` and `lineCount`
  app/docker/components/log-viewer/log-viewer.js
  app/docker/components/log-viewer/logViewer.html
  app/docker/components/log-viewer/logViewerController.js
  app/docker/services/containerService.js
  app/docker/services/serviceService.js
  app/docker/services/taskService.js
  app/docker/views/containers/logs/containerLogsController.js
  app/docker/views/containers/logs/containerlogs.html
  app/docker/views/services/logs/serviceLogsController.js
  app/docker/views/services/logs/servicelogs.html
  app/docker/views/tasks/logs/taskLogsController.js
  app/docker/views/tasks/logs/tasklogs.html
Labels: status/5-merge

#2389 feat(ux): normalize quick actions buttons
  app/docker/components/container-quick-actions/containerQuickActions.html
  app/docker/components/container-quick-actions/containerQuickActions.js
  app/docker/components/datatables/containers-datatable/containersDatatable.html
  app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatable.html
  app/docker/components/datatables/service-tasks-datatable/serviceTasksDatatableController.js
  app/docker/components/datatables/tasks-datatable/tasksDatatable.html
  app/docker/components/datatables/tasks-datatable/tasksDatatable.js
  app/docker/components/datatables/tasks-datatable/tasksDatatableController.js
Labels: status/5-merge
