Repository portainer/portainer, pull requests merged in 2018-12, with the labels that each got.

#2510 chore(docker): update docker binary version to 18.09.0
  gruntfile.js
Labels: dep/docker-cli, kind/enhancement

#2493 feat(containers-stats): add refresh rate of 1 and 3 seconds
  app/docker/views/containers/stats/containerstats.html
Labels: status/5-merge

#2323 Fix env vars sent with default values
  app/portainer/components/forms/template-form/template-form.js
  app/portainer/views/templates/templatesController.js
Labels: status/5-merge

#2500 Stop portainer instance after 5 minutes if no admin was created
  api/cmd/portainer/main.go
Labels: status/4-test

#2472 feat2439: add the capability to enable/disable the host features
  api/bolt/migrator/migrate_dbversion14.go
  api/bolt/migrator/migrator.go
  api/cmd/portainer/main.go
  api/errors.go
  api/http/handler/schedules/handler.go
  api/http/handler/schedules/schedule_create.go
  api/http/handler/schedules/schedule_delete.go
  api/http/handler/schedules/schedule_file.go
  api/http/handler/schedules/schedule_inspect.go
  api/http/handler/schedules/schedule_list.go
  api/http/handler/schedules/schedule_tasks.go
  api/http/handler/schedules/schedule_update.go
  api/http/handler/settings/settings_public.go
  api/http/handler/settings/settings_update.go
  api/http/server.go
  api/portainer.go
  app/docker/components/host-overview/host-overview.html
  app/docker/components/host-overview/host-overview.js
  app/docker/views/host/host-view-controller.js
  app/docker/views/host/host-view.html
  app/docker/views/nodes/node-details/node-details-view-controller.js
  app/docker/views/nodes/node-details/node-details-view.html
  app/portainer/models/settings.js
  app/portainer/services/stateManager.js
  app/portainer/views/settings/settings.html
  app/portainer/views/settings/settingsController.js
  app/portainer/views/sidebar/sidebar.html
Labels: status/2-technical-review

#2425 feat(ui): persist search criteria for containers, services and stacks
  app/agent/components/files-datatable/files-datatable.html
  app/azure/components/datatables/containergroups-datatable/containerGroupsDatatable.html
  app/docker/components/datatables/configs-datatable/configsDatatable.html
  app/docker/components/datatables/containers-datatable/containersDatatable.html
  app/docker/components/datatables/containers-datatable/containersDatatableController.js
  app/docker/components/datatables/events-datatable/eventsDatatable.html
  app/docker/components/datatables/host-jobs-datatable/jobsDatatable.html
  app/docker/components/datatables/host-jobs-datatable/jobsDatatableController.js
  app/docker/components/datatables/images-datatable/imagesDatatable.html
  app/docker/components/datatables/images-datatable/imagesDatatableController.js
  app/docker/components/datatables/macvlan-nodes-datatable/macvlanNodesDatatable.html
  app/docker/components/datatables/networks-datatable/networksDatatable.html
  app/docker/components/datatables/node-tasks-datatable/nodeTasksDatatable.html
  app/docker/components/datatables/nodes-datatable/nodesDatatable.html
  app/docker/components/datatables/secrets-datatable/secretsDatatable.html
  app/docker/components/datatables/services-datatable/servicesDatatable.html
  app/docker/components/datatables/services-datatable/servicesDatatableController.js
  app/docker/components/datatables/tasks-datatable/tasksDatatable.html
  app/docker/components/datatables/tasks-datatable/tasksDatatableController.js
  app/docker/components/datatables/volumes-datatable/volumesDatatable.html
  app/docker/components/datatables/volumes-datatable/volumesDatatableController.js
  app/extensions/storidge/components/cluster-events-datatable/storidgeClusterEventsDatatable.html
  app/extensions/storidge/components/nodes-datatable/storidgeNodesDatatable.html
  app/extensions/storidge/components/profiles-datatable/storidgeProfilesDatatable.html
  app/portainer/components/access-table/accessTable.html
  app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
  app/portainer/components/datatables/genericDatatableController.js
  app/portainer/components/datatables/groups-datatable/groupsDatatable.html
  app/portainer/components/datatables/registries-datatable/registriesDatatable.html
  app/portainer/components/datatables/stacks-datatable/stacksDatatable.html
  app/portainer/components/datatables/stacks-datatable/stacksDatatableController.js
  app/portainer/components/datatables/tags-datatable/tagsDatatable.html
  app/portainer/components/datatables/teams-datatable/teamsDatatable.html
  app/portainer/components/datatables/users-datatable/usersDatatable.html
  app/portainer/components/endpoint-list/endpoint-list-controller.js
  app/portainer/components/endpoint-list/endpoint-list.js
  app/portainer/components/endpoint-list/endpointList.html
  app/portainer/components/group-association-table/groupAssociationTable.html
  app/portainer/components/template-list/template-list-controller.js
  app/portainer/components/template-list/template-list.js
  app/portainer/components/template-list/templateList.html
  app/portainer/services/datatableService.js
  app/portainer/services/localStorage.js
  app/portainer/views/home/home.html
  app/portainer/views/templates/templates.html
Labels: status/5-merge

#2449 Feat AppVeyor Multi Architecture Support
  appveyor-ci.yml
  appveyor-release.yml
  build/build_binary.ps1
  build/build_binary.sh
  build/build_in_container.sh
  build/ci-linux.sh
  build/ci-windows.ps1
  build/download_docker_binary.ps1
  build/download_docker_binary.sh
  build/release-linux.sh
  build/release-windows.ps1
  gruntfile.js
Labels: area/build-system, area/ci, status/5-merge

#2537 feat(api): migrate template data logo URLs
  api/bolt/datastore.go
  api/bolt/migrator/migrate_dbversion14.go
  api/bolt/migrator/migrator.go
  api/portainer.go
Labels: area/templates, kind/refactor

#2539 feat(api): update DigitalSignatureService
  api/crypto/ecdsa.go
  api/docker/client.go
  api/exec/swarm_stack.go
  api/http/handler/websocket/websocket_exec.go
  api/http/proxy/docker_transport.go
  api/portainer.go
Labels: kind/refactor
