Repository portainer/portainer, pull requests merged in 2018-04, with the labels that each got.

#1720 refactor(project): remove Swarm standalone support
  app/docker/components/datatables/containers-datatable/containersDatatable.html
  app/docker/components/datatables/containers-datatable/containersDatatable.js
  app/docker/components/datatables/nodes-ss-datatable/nodesSSDatatable.html
  app/docker/components/datatables/nodes-ss-datatable/nodesSSDatatable.js
  app/docker/filters/filters.js
  app/docker/helpers/infoHelper.js
  app/docker/services/networkService.js
  app/docker/views/containers/containers.html
  app/docker/views/containers/containersController.js
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
  app/docker/views/containers/edit/containerController.js
  app/docker/views/dashboard/dashboard.html
  app/docker/views/images/imagesController.js
  app/docker/views/networks/create/createNetworkController.js
  app/docker/views/swarm/swarm.html
  app/docker/views/templates/templates.html
  app/docker/views/templates/templatesController.js
  app/docker/views/volumes/create/createVolumeController.js
  app/portainer/helpers/templateHelper.js
Labels: kind/refactor

#1776 feat(stack): Add scaling arrows to services list in stack view
  app/docker/views/stacks/edit/stack.html
  app/docker/views/stacks/edit/stackController.js
  app/portainer/components/datatables/stack-services-datatable/stackServicesDatatable.html
  app/portainer/components/datatables/stack-services-datatable/stackServicesDatatable.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1777 feat(swarm-visualizer): save settings to local storage
  app/docker/views/swarm/visualizer/swarmVisualizerController.js
  app/docker/views/swarm/visualizer/swarmvisualizer.html
  app/portainer/services/localStorage.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1809 #1808 fix(api): add json content-type to all json API responses
  api/http/error/error.go
  api/http/handler/handler.go
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1812 docs(api): add missing supported resource control types
  api/swagger.yaml
Labels: area/api, area/documentation

#1791 Force to remove charset from content-type of post/put/patch.
  app/config.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1803 Fix 1797 push image authentication
  api/http/proxy/transport.go
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1837 feat(endpoint-groups): add endpoint-groups
  api/bolt/datastore.go
  api/bolt/endpoint_group_service.go
  api/bolt/internal/internal.go
  api/bolt/migrate_dbversion8.go
  api/bolt/migrator.go
  api/cmd/portainer/main.go
  api/errors.go
  api/http/handler/docker.go
  api/http/handler/endpoint.go
  api/http/handler/endpoint_group.go
  api/http/handler/extensions/storidge.go
  api/http/handler/handler.go
  api/http/security/authorization.go
  api/http/security/filter.go
  api/http/server.go
  api/portainer.go
  app/constants.js
  app/portainer/__module.js
  app/portainer/components/access-table/access-table.js
  app/portainer/components/access-table/accessTable.html
  app/portainer/components/accessManagement/por-access-management.js
  app/portainer/components/accessManagement/porAccessManagement.html
  app/portainer/components/accessManagement/porAccessManagementController.js
  app/portainer/components/datatables/endpoints-datatable/endpointsDatatable.html
  app/portainer/components/datatables/groups-datatable/groupsDatatable.html
  app/portainer/components/datatables/groups-datatable/groupsDatatable.js
  app/portainer/components/endpoint-selector/endpoint-selector.js
  app/portainer/components/endpoint-selector/endpointSelector.html
  app/portainer/components/endpoint-selector/endpointSelectorController.js
  app/portainer/components/forms/group-form/group-form.js
  app/portainer/components/forms/group-form/groupForm.html
  app/portainer/components/group-association-table/group-association-table.js
  app/portainer/components/group-association-table/groupAssociationTable.html
  app/portainer/helpers/endpointHelper.js
  app/portainer/models/access.js
  app/portainer/models/group.js
  app/portainer/rest/group.js
  app/portainer/services/api/accessService.js
  app/portainer/services/api/endpointService.js
  app/portainer/services/api/groupService.js
  app/portainer/services/fileUpload.js
  app/portainer/views/endpoints/access/endpointAccess.html
  app/portainer/views/endpoints/access/endpointAccessController.js
  app/portainer/views/endpoints/edit/endpoint.html
  app/portainer/views/endpoints/edit/endpointController.js
  app/portainer/views/endpoints/endpoints.html
  app/portainer/views/endpoints/endpointsController.js
  app/portainer/views/groups/access/groupAccess.html
  app/portainer/views/groups/access/groupAccessController.js
  app/portainer/views/groups/create/createGroupController.js
  app/portainer/views/groups/create/creategroup.html
  app/portainer/views/groups/edit/group.html
  app/portainer/views/groups/edit/groupController.js
  app/portainer/views/groups/groups.html
  app/portainer/views/groups/groupsController.js
  app/portainer/views/init/endpoint/initEndpointController.js
  app/portainer/views/sidebar/sidebar.html
  app/portainer/views/sidebar/sidebarController.js
Labels: docker-image-available
