Repository portainer/portainer, pull requests merged in 2018-11, with the labels that each got.

#2390 Schedule api
  api/bolt/datastore.go
  api/bolt/schedule/schedule.go
  api/cmd/portainer/main.go
  api/cron/job_endpoint_snapshot.go
  api/cron/scheduler.go
  api/cron/task_endpoint_sync.go
  api/cron/task_script.go
  api/cron/task_snapshot.go
  api/docker/job.go
  api/filesystem/filesystem.go
  api/http/handler/handler.go
  api/http/handler/schedules/handler.go
  api/http/handler/schedules/schedule_create.go
  api/http/handler/schedules/schedule_delete.go
  api/http/handler/schedules/schedule_inspect.go
  api/http/handler/schedules/schedule_list.go
  api/http/handler/schedules/schedule_update.go
  api/http/handler/settings/settings_update.go
  api/http/server.go
  api/portainer.go
Labels: status/5-merge

#2414 feat(schedules): add schedules UI mockups
  api/http/handler/schedules/schedule_create.go
  app/constants.js
  app/portainer/__module.js
  app/portainer/components/datatables/schedules-datatable/schedulesDatatable.html
  app/portainer/components/datatables/schedules-datatable/schedulesDatatable.js
  app/portainer/components/datatables/schedules-datatable/schedulesDatatableController.js
  app/portainer/components/forms/schedule-form/schedule-form.js
  app/portainer/components/forms/schedule-form/scheduleForm.html
  app/portainer/components/multi-endpoint-selector/multi-endpoint-selector.js
  app/portainer/components/multi-endpoint-selector/multiEndpointSelector.html
  app/portainer/components/multi-endpoint-selector/multiEndpointSelectorController.js
  app/portainer/models/schedule.js
  app/portainer/rest/schedule.js
  app/portainer/services/api/scheduleService.js
  app/portainer/services/fileUpload.js
  app/portainer/views/schedules/create/createScheduleController.js
  app/portainer/views/schedules/create/createschedule.html
  app/portainer/views/schedules/edit/schedule.html
  app/portainer/views/schedules/edit/scheduleController.js
  app/portainer/views/schedules/schedules.html
  app/portainer/views/schedules/schedulesController.js
  app/portainer/views/sidebar/sidebar.html
Labels: status/4-test

#2419 feat(containers): allow escaped quotes in command field
  app/docker/helpers/containerHelper.js
Labels: status/5-merge

#2429 Fixing the CPU and Memory charts on Windows containers
  app/docker/models/container.js
  app/docker/views/containers/stats/containerStatsController.js
  app/portainer/services/chartService.js
Labels: status/5-merge

#2454 fix2443: offline browsing performance
  api/http/handler/endpointproxy/proxy_docker.go
  app/docker/interceptors/containersInterceptor.js
  app/docker/interceptors/imagesInterceptor.js
  app/docker/interceptors/infoInterceptor.js
  app/docker/interceptors/networksInterceptor.js
  app/docker/interceptors/versionInterceptor.js
  app/docker/interceptors/volumesInterceptor.js
  app/portainer/interceptors/endpointStatusInterceptor.js
Labels: status/5-merge

#2465 style(dashboard): change blocklist-item border color
  assets/css/app.css
Labels: status/5-merge

#2466 feat(motd): relocate motd file URL and always return 200
  api/http/handler/motd/motd.go
  api/portainer.go
  app/portainer/views/home/home.html
Labels: area/motd, kind/enhancement

#2471 feat2469: add url to endpoints list
  app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
  app/portainer/components/endpoint-list/endpoint-list-controller.js
  app/portainer/components/endpoint-list/endpointList.html
Labels: status/5-merge

#2486 feat(api): support AGENT_SECRET environment variable
  api/cmd/portainer/main.go
  api/crypto/ecdsa.go
  api/docker/client.go
  api/exec/swarm_stack.go
  api/http/handler/websocket/websocket_exec.go
  api/http/proxy/docker_transport.go
  api/portainer.go
Labels: area/agent, kind/enhancement

#2484 fix2480: containers-stats js error
  app/docker/models/container.js
Labels: status/5-merge

#2452 chore(terminal): updated xterm to 3.8.0 version
  package.json
  yarn.lock
Labels: status/5-merge

#2488 feat(api): filter LDAP password from settings response
  api/http/handler/settings/handler.go
  api/http/handler/settings/settings_inspect.go
  api/portainer.go
Labels: area/security, area/settings, authentication/ldap

#2487 feat2442: container image create visual feedback
  app/docker/views/containers/edit/containerController.js
Labels: status/5-merge

#2474 fix2473: use plural form only when required
  app/docker/views/dashboard/dashboard.html
  app/portainer/components/endpoint-list/endpoint-item/endpointItem.html
Labels: status/5-merge

#2495 add start and start:server scripts
  package.json
Labels: area/build-system, kind/enhancement, status/5-merge

#2502 fix(containers-console): strange console behaviour on error at start
  app/docker/views/containers/console/containerConsoleController.js
Labels: area/UX, area/container-console, kind/enhancement

#2503 fix(images-upload): error on tar upload with multiple images inside
  app/portainer/services/fileUpload.js
Labels: area/image-upload, kind/bug
