Repository portainer/portainer, pull requests merged in 2018-03, with the labels that each got.

#1683 #1597 feat(swarm-visualizer): swarm visualizer color by service
  app/docker/views/swarm/visualizer/swarmVisualizerController.js
  app/docker/views/swarm/visualizer/swarmvisualizer.html
  assets/css/app.css
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1686 refactor(swarm-visualizer): move task border logic to a filter
  app/docker/filters/filters.js
  app/docker/views/swarm/visualizer/swarmVisualizerController.js
  app/docker/views/swarm/visualizer/swarmvisualizer.html
Labels: kind/refactor

#1693 feat(storidge): add extension check on endpoint switch
  api/http/handler/extensions.go
  app/docker/views/services/logs/serviceLogsController.js
  app/portainer/rest/extension.js
  app/portainer/services/api/endpointService.js
  app/portainer/services/api/extensionService.js
  app/portainer/services/extensionManager.js
  app/portainer/views/auth/authController.js
  app/portainer/views/endpoints/endpointsController.js
  app/portainer/views/sidebar/sidebarController.js
Labels: docker-image-available, extension/storidge, kind/enhancement

#1709 fix(services): fix services log view breadcrumb link
  app/docker/views/services/logs/servicelogs.html
Labels: area/service-logs, contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated, kind/bug

#1713 feat(log-viewer): use only one switch to manage collection/autoscroll
  app/docker/components/log-viewer/logViewer.html
  app/docker/components/log-viewer/logViewerController.js
Labels: area/container-logs, area/service-logs, area/task-logs, kind/enhancement

#1719 fix(api): ignore directory existence check and use os.MkdirAll
  api/filesystem/filesystem.go
Labels: docker-image-available, status/awaiting-feedback

#1475 chore(build-system) use regular vendor files, ignore (pre)minified
  gruntfile.js
  vendor.yml
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1715 feat(image-details): display image layer depth and sort by it by default (#1706)
  app/docker/models/imageLayer.js
  app/docker/services/imageService.js
  app/docker/views/images/edit/image.html
  app/docker/views/images/edit/imageController.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1727 style(app): update icon style
  app/docker/components/datatables/configs-datatable/configsDatatable.html
  app/docker/components/datatables/containers-datatable/containersDatatable.html
  app/docker/components/datatables/nodes-datatable/nodesDatatable.html
  app/docker/components/datatables/services-datatable/servicesDatatable.html
  app/docker/components/datatables/tasks-datatable/tasksDatatable.html
  app/docker/components/dockerSidebarContent/dockerSidebarContent.html
  app/docker/views/containers/edit/container.html
  app/docker/views/containers/inspect/containerinspect.html
  app/docker/views/images/build/buildimage.html
  app/docker/views/images/edit/image.html
  app/docker/views/services/edit/service.html
  app/docker/views/stacks/create/createstack.html
  app/docker/views/tasks/edit/task.html
  app/portainer/components/datatables/users-datatable/usersDatatable.html
  app/portainer/components/header-title.js
  app/portainer/views/about/about.html
  vendor.yml
Labels: kind/style

#1750 fix(extensions): use an empty object instead of a null value when reg…
  app/portainer/services/extensionManager.js
Labels: docker-image-available, status/awaiting-feedback

#1747 fix(templates): fix app templates stack deployment
  app/docker/views/templates/templatesController.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1751 fix(api): manage registry authentication in the API
  api/http/handler/dockerhub.go
  api/http/handler/registry.go
  api/http/proxy/factory.go
  api/http/proxy/manager.go
  api/http/proxy/registry.go
  api/http/proxy/transport.go
  api/http/security/authorization.go
  api/http/security/filter.go
  api/http/server.go
  api/portainer.go
  app/portainer/services/api/registryService.js
Labels: docker-image-available

#1697 Enable timestamps by default in logs
  app/docker/components/log-viewer/log-viewer.js
  app/docker/components/log-viewer/logViewer.html
  app/docker/views/containers/logs/containerLogsController.js
  app/docker/views/containers/logs/containerlogs.html
  app/docker/views/services/logs/serviceLogsController.js
  app/docker/views/services/logs/servicelogs.html
  app/docker/views/tasks/logs/taskLogsController.js
  app/docker/views/tasks/logs/tasklogs.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1773 style(services): format stop grace period (fix #1772)
  app/docker/views/services/edit/serviceController.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1770 style(dashbard) avoid long container name to display on new line
  assets/css/app.css
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated
