Repository portainer/portainer, pull requests merged in 2018-06, with the labels that each got.

#1907 fix(container): recreate container with multiple networks
  app/docker/views/containers/create/createContainerController.js
  app/docker/views/containers/create/createcontainer.html
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated

#1964 fix(api): review security policies when creating/updating a resource …
  api/http/handler/resourcecontrols/resourcecontrol_update.go
  api/http/security/authorization.go
Labels: area/UAC

#1971 feat(tags): add the ability to manage tags
  api/bolt/datastore.go
  api/bolt/internal/internal.go
  api/bolt/migrate_dbversion11.go
  api/bolt/migrator.go
  api/bolt/tag_service.go
  api/cmd/portainer/main.go
  api/errors.go
  api/http/handler/endpointgroups/endpointgroup_create.go
  api/http/handler/endpointgroups/endpointgroup_update.go
  api/http/handler/endpoints/endpoint_create.go
  api/http/handler/endpoints/endpoint_update.go
  api/http/handler/handler.go
  api/http/handler/tags/handler.go
  api/http/handler/tags/tag_create.go
  api/http/handler/tags/tag_delete.go
  api/http/handler/tags/tag_list.go
  api/http/server.go
  api/portainer.go
  api/swagger.yaml
  app/constants.js
  app/portainer/__module.js
  app/portainer/components/datatables/tags-datatable/tagsDatatable.html
  app/portainer/components/datatables/tags-datatable/tagsDatatable.js
  app/portainer/components/forms/group-form/group-form.js
  app/portainer/components/forms/group-form/groupForm.html
  app/portainer/components/tag-selector/tag-selector.js
  app/portainer/components/tag-selector/tagSelector.html
  app/portainer/components/tag-selector/tagSelectorController.js
  app/portainer/models/group.js
  app/portainer/models/tag.js
  app/portainer/rest/tag.js
  app/portainer/services/api/endpointService.js
  app/portainer/services/api/tagService.js
  app/portainer/services/fileUpload.js
  app/portainer/views/endpoints/create/createEndpointController.js
  app/portainer/views/endpoints/create/createendpoint.html
  app/portainer/views/endpoints/edit/endpoint.html
  app/portainer/views/endpoints/edit/endpointController.js
  app/portainer/views/groups/create/createGroupController.js
  app/portainer/views/groups/create/creategroup.html
  app/portainer/views/groups/edit/group.html
  app/portainer/views/groups/edit/groupController.js
  app/portainer/views/init/endpoint/initEndpointController.js
  app/portainer/views/sidebar/sidebar.html
  app/portainer/views/tags/tags.html
  app/portainer/views/tags/tagsController.js
  assets/css/app.css
  package.json
  vendor.yml
  yarn.lock
Labels: area/tags, kind/feature

#1979 fix(api): add an authenticated access policy to the websocket endpoint
  api/http/handler/endpointproxy/handler.go
  api/http/handler/endpointproxy/proxy_azure.go
  api/http/handler/endpointproxy/proxy_docker.go
  api/http/handler/endpointproxy/proxy_storidge.go
  api/http/handler/stacks/handler.go
  api/http/handler/stacks/stack_create.go
  api/http/handler/stacks/stack_delete.go
  api/http/handler/websocket/handler.go
  api/http/handler/websocket/websocket_exec.go
  api/http/security/authorization.go
  api/http/security/bouncer.go
  api/http/security/filter.go
  api/http/server.go
  app/docker/views/containers/console/containerConsoleController.js
Labels: area/security

#1980 refactor(api): use a standard stack identifier
  api/bolt/datastore.go
  api/bolt/migrate_dbversion11.go
  api/bolt/migrator.go
  api/bolt/stack_service.go
  api/cmd/portainer/main.go
  api/filesystem/filesystem.go
  api/http/handler/stacks/create_compose_stack.go
  api/http/handler/stacks/create_swarm_stack.go
  api/http/handler/stacks/stack_create.go
  api/http/handler/stacks/stack_delete.go
  api/http/handler/stacks/stack_file.go
  api/http/handler/stacks/stack_inspect.go
  api/http/handler/stacks/stack_update.go
  api/portainer.go
Labels: kind/refactor

#1984 feat(services): add the ability to pull latest image when updating a …
  app/docker/components/datatables/services-datatable/actions/servicesDatatableActionsController.js
  app/docker/helpers/imageHelper.js
  app/docker/models/service.js
  app/docker/rest/service.js
  app/docker/views/services/edit/serviceController.js
  app/portainer/services/modalService.js
Labels: kind/workaround

#1522 #1486 fix(images): create tags from RepoDigests when no tags
  app/docker/services/imageService.js
Labels: contrib/func-review-approved, contrib/ready-to-merge, contrib/tech-review-approved, contrib/tests-validated
