Repository portainer/portainer, pull requests merged in 2019-03, with the labels that each got.

#2749 feat(dep): update docker binary version to 18.09.3
  gruntfile.js
Labels: dep/docker-cli

#2760 refactor(api): fix lint issues
  api/http/proxy/manager.go
Labels: kind/refactor

#2772 style(containers): change order of container action buttons to match …
  app/docker/views/containers/edit/container.html
Labels: area/container-details, kind/style
