Repository portainer/portainer, pull requests merged in 2019-11, with the labels that each got.

#2996 fix(container): Fix bad env in container creation
  app/docker/views/containers/create/createContainerController.js
Labels: status/5-merge

#3327 Revert "fix(api): fix invalid resource control check"
  api/http/proxy/docker_transport.go
Labels: kind/rollback-feature

#2655 Container label value allow null
  app/docker/views/containers/create/createContainerController.js
  app/portainer/helpers/templateHelper.js
Labels: shortlist, status/5-merge

#3328 #2844 fix(cli): remove the logging of the hashed password of the admin user
  api/cmd/portainer/main.go
Labels: status/5-merge
