Repository portainer/portainer, pull requests merged in 2019-01, with the labels that each got.

#2595 fix2556: frequent offline mode
  app/portainer/interceptors/endpointStatusInterceptor.js
  app/portainer/services/endpointProvider.js
Labels: changes-required, status/5-merge

#2545 fix repository reload got error in remove tags
  app/extensions/registry-management/views/repositories/edit/registryRepositoryController.js
Labels: bug/confirmed, extension/registry-manager, kind/bug

#2632 dep(bootstrap): update bootstrap version to 3.4.0
  package.json
  yarn.lock
Labels: area/security, kind/update-dependency

#2670 Fix to allow DevOps pipeline to leverage webpack
  build/build_binary.ps1
  build/build_binary_devops.ps1
  gruntfile.js
Labels: area/ci
